"""Contains variable to update SpaCy stop words and lemmatization rules"""

SCI_PAPER_STOP = {"additional", "answer", "approach", "art", "beebe",
                  "breitinger", "casey", "challenge", "choo", "concept",
                  "conduct", "data", "describe", "discuss", "enumerate",
                  "experiment", "experimental", "face", "false", "fig",
                  "figs", "focus", "follow", "follows:-", "formula", "future",
                  "garfinkel", "general", "ieee", "illustrate", "important",
                  "information", "interesting", "keyword", "list",
                  "literature", "method", "methodology", "model", "note",
                  "overview", "page", "paper", "point", "previous", "prior",
                  "propose", "purpose", "question", "quick", "®", "result",
                  "related", "relevant", "research", "review", "roussev",
                  "search", "section", "spafford", "state", "subsection",
                  "table", "term", "™", "useful", "view", "×", "work"}

GENERIC_STOP = {"activity", "applicable", "autopsy", "carrier", "calculate",
                "consideration", "contain", "customer", "different",
                "facilitate", "feasible", "good", "huge", "increase",
                "issue", "know", "large", "leverage", "mechanism", "new",
                "organizational", "pertinent", "reasonable", "requirement",
                "satisfy", "scale", "scalpel", "simplicity", "sophisticated",
                "total", "underlie", "unused", "usage", "use", "usefulness",
                "utilization", "valuable"}

DIGTAL_FORENSICS_STOP = {"agency", "analyse", "analysis", "application",
                         "client", "clue", "community", "computing",
                         "computation", "computational", "credential", "crime",
                         "custody", "cyber", "dataset", "default", "device",
                         "digital", "domain", "enforcement", "estimation",
                         "evidence", "examiner", "forensic", "forensics",
                         "ground", "insight", "investigation", "investigator",
                         "laboratory", "law", "practitioner", "process",
                         "programming", "proof", "scenario", "scene", "setup",
                         "similarity", "taxonomy", "technique", "tool",
                         "truth", "user", "vendor"}

DUPLICATES = {
    "anonymous": "anonymity",
    "artefact": "artifact",
    "authenticate": "authentication",
    "authentification": "authentication",
    "blockchain technology": "blockchain",
    "carving": "carve",
    "cell phone": "mobile phone",
    "cloud provider": "cloud service provider",
    "cloud storage service": "cloud storage",
    "content file": "file content",
    "directory file": "file directory",
    "e mail": "email",
    "executable file": "executable",
    "extract feature": "feature extraction",
    "filesystem": "file system",
    "file download": "download file",
    "file extract": "extract file",
    "file recover": "recover file",
    "recover filey": "recover file",
    "filtering": "filter",
    "folder": "directory",
    "hard drive": "hard disk drive",
    "hdd": "hard disk drive",
    "high accuracy": "accuracy",
    "high entropy": "entropy",
    "high frequency": "frequency",
    "image camera": "camera image",
    "jpeg file": "jpeg image",
    "leakage": "leak",
    "metadata file": "file metadata",
    "microsoft windows": "windows",
    "national institute standards technology": "nist",
    "pdf document": "pdf file",
    "pre processing": "preprocess",
    "preprocesse": "preprocess",
    "request": "query",
    "reverse engineering": "reverse engineer",
    "size file": "file size",
    "smart phone": "smartphone",
    "social medium": "social network",
    "steganographic": "steganography",
    "stego": "steganography",
    "store file": "file store",
    "svm": "support vector machine",
    "system file": "file system",
    "time date": "date time",
    "time stamp": "timestamp",
    "type file": "file type",
    "windows operating system": "windows",
}
